"""Phase 3: test two low-risk, non-search improvements to LE-GRA MVP,
identified from (a) a factual correction found while reviewing the Phase 1
clean validation code, and (b) the project's own historical P0 finding.

Why this script exists
-----------------------
Phase 1 (`run_clean_resource_cost_validation.py`) trained LE-GRA with
`feature_mode="history_cost"` while `Multi-feature k-means` clustered on
`feature_mode="full"` -- LE-GRA still won on LESS information, which is a
more promising signal than an apples-to-apples comparison would have been,
but it also means the two methods were never fairly compared on equal
information. Separately, the project's own `P0_VALIDATION_STUDY_ZH.md`
already found that selecting the training epoch by validation *contrastive
loss* is not a reliable proxy for downstream utility -- but nothing ever
tried selecting by validation *utility* directly, which closes that gap
properly instead of abandoning validation-based selection altogether.

This script is a 2x2 ablation, not a search: it fixes exactly two candidate
changes in advance and reports all four cells, whichever way they come out.

Pre-registered protocol
------------------------
- Same 5 scenario_modes x 3 load_levels x 6 seeds x Kmax=3 x
  train=60/test=30 as Phase 1, for direct comparability of numbers.
- Baselines (No grouping, CQI/Resource-cost/Multi-feature k-means, Offline
  teacher) are re-evaluated fresh on the scenarios generated by *this*
  script rather than reusing Phase 1's CSV, because the RNG draw sequence
  differs slightly between scripts even with the same seed -- reusing
  Phase 1's numbers here would silently break the pairing.
- Teacher labels (for train) and teacher groups (for test, used for the
  Offline teacher baseline) are computed ONCE per (scenario_mode,
  load_level, seed) job and reused across all four LE-GRA variants. This
  is a compute optimization, not a validity change: `offline_teacher_groups`
  reads `rb_rates`/`previous_quality`/`rb_available`, never
  `scenario.features`, so it does not depend on `feature_mode` at all.
- Four LE-GRA variants (2x2), epochs=12 for all of them (fixed so the
  validation-based variants have a real early-stopping budget to select
  from; the P0 study used the same epoch count):
    1. history_cost_none  -- current repo default (Phase 1's LE-GRA)
    2. full_none          -- same as (1) but feature_mode="full"
    3. history_cost_utility -- same as (1) but epoch selected by highest
       mean DP-utility (not contrastive loss) on a held-out validation
       split (validation_fraction=0.2, matching the historical P0 study),
       then refit on the full training set for that many epochs
    4. full_utility       -- both changes combined
- No scenario is filtered, hand-edited, or selected post-hoc; the protocol
  above is fixed before running.
"""

from __future__ import annotations

import argparse
import csv
import random
import time
from pathlib import Path

import numpy as np

import le_gra_mvp as mvp
from run_standard_matrix import LOAD_RATIOS, progress

VARIANTS = [
    ("history_cost_none", "history_cost", "none"),
    ("full_none", "full", "none"),
    ("history_cost_utility", "history_cost", "utility"),
    ("full_utility", "full", "utility"),
]

BASELINE_METHODS = ["No grouping", "CQI k-means", "Resource-cost k-means", "Multi-feature k-means", "Offline teacher"]
DEFAULT_SCENARIO_MODES = ["aligned", "ambiguous", "mixed", "anti_cqi_hard", "corridor_general"]
DEFAULT_SEEDS = [9, 17, 23, 31, 42, 58]


def generate_splits(args, scenario_mode: str, seed: int, load_level: str) -> tuple[list, list]:
    mvp.set_seed(seed)
    dispersions = ["high", "mid", "low"]
    rb_budget_ratio = LOAD_RATIOS[load_level]
    train = [
        mvp.generate_scenario(args.users, args.rbs, random.choice(dispersions), scenario_mode, rb_budget_ratio=rb_budget_ratio)
        for _ in range(args.train_scenarios)
    ]
    test = [
        mvp.generate_scenario(args.users, args.rbs, random.choice(dispersions), scenario_mode, rb_budget_ratio=rb_budget_ratio)
        for _ in range(args.test_scenarios)
    ]
    return train, test


def train_variant(
    train: list,
    test: list,
    teacher_groups_all: list,
    feature_mode: str,
    max_groups: int,
    switch_beta: float,
    epochs: int,
    selection_metric: str,
    validation_fraction: float,
    pair_sampling: str,
    pairs_per_class: int,
    kmeans_n_init: int,
) -> mvp.MLPEncoder:
    mvp.apply_feature_mode(train, test, feature_mode)
    mvp.normalize_features(train, test)

    validation_count = 0
    if selection_metric == "utility" and validation_fraction > 0.0 and len(train) >= 3:
        validation_count = max(1, int(round(len(train) * validation_fraction)))
        validation_count = min(validation_count, len(train) - 1)
    fit = train[: len(train) - validation_count] if validation_count else train
    validation = train[len(train) - validation_count :] if validation_count else []

    teacher_labels_all = [mvp.pairwise_labels(g, len(train[0].cqi_now)) for g in teacher_groups_all]
    fit_labels = teacher_labels_all[: len(fit)]

    model = mvp.MLPEncoder(input_dim=train[0].features.shape[1], hidden_dim=48, embedding_dim=8, lr=0.01)
    initial_state = model.get_state()
    best_state = model.get_state()
    best_epoch = 0
    best_score = -float("inf")

    for epoch in range(1, epochs + 1):
        order = list(range(len(fit)))
        random.shuffle(order)
        for idx in order:
            model.train_step(fit[idx].features, fit_labels[idx], pair_sampling=pair_sampling, max_pairs_per_class=pairs_per_class)

        if selection_metric == "utility" and validation:
            utilities = []
            for scenario in validation:
                groups = mvp.learned_grouping(scenario, model, max_groups, switch_beta, kmeans_n_init)
                utilities.append(mvp.allocate_and_evaluate(groups, scenario, switch_beta).utility)
            score = float(np.mean(utilities))
            if score > best_score:
                best_score = score
                best_epoch = epoch
                best_state = model.get_state()
        else:
            best_epoch = epoch
            best_state = model.get_state()

    if selection_metric == "utility" and validation:
        model.set_state(initial_state)
        for _ in range(best_epoch):
            order = list(range(len(train)))
            random.shuffle(order)
            for idx in order:
                model.train_step(train[idx].features, teacher_labels_all[idx], pair_sampling=pair_sampling, max_pairs_per_class=pairs_per_class)
    else:
        model.set_state(best_state)

    return model


def run_matrix(args) -> list[dict]:
    rows = []
    total_jobs = len(args.scenario_modes) * len(args.load_levels) * len(args.seeds)
    job = 0
    started = time.perf_counter()
    for scenario_mode in args.scenario_modes:
        for load_level in args.load_levels:
            for seed in args.seeds:
                job += 1
                label = f"job {job}/{total_jobs} mode={scenario_mode} load={load_level} seed={seed}"
                tags = {"scenario_mode": scenario_mode, "load_level": load_level, "seed": seed}
                random.seed(seed)
                train, test = generate_splits(args, scenario_mode, seed, load_level)

                progress(f"{label} teacher labels ({time.perf_counter() - started:.1f}s elapsed)")
                teacher_groups_train = [mvp.offline_teacher_groups(s, args.kmax, args.switch_beta) for s in train]
                teacher_groups_test = [mvp.offline_teacher_groups(s, args.kmax, args.switch_beta) for s in test]

                baseline_fns = {
                    "No grouping": lambda s: mvp.no_grouping(s),
                    "CQI k-means": lambda s: mvp.cqi_kmeans_grouping(s, args.kmax, args.switch_beta, args.kmeans_n_init),
                    "Resource-cost k-means": lambda s: mvp.resource_cost_kmeans_grouping(s, args.kmax, args.switch_beta, args.kmeans_n_init),
                    "Multi-feature k-means": lambda s: mvp.multi_feature_kmeans_grouping(
                        s, args.kmax, args.switch_beta, feature_mode="full", kmeans_n_init=args.kmeans_n_init
                    ),
                }
                for method_name, fn in baseline_fns.items():
                    for test_index, scenario in enumerate(test):
                        groups = fn(scenario)
                        utility = mvp.allocate_and_evaluate(groups, scenario, args.switch_beta).utility
                        rows.append({**tags, "method": method_name, "test_index": test_index, "utility": utility})
                for test_index, (scenario, groups) in enumerate(zip(test, teacher_groups_test)):
                    utility = mvp.allocate_and_evaluate(groups, scenario, args.switch_beta).utility
                    rows.append({**tags, "method": "Offline teacher", "test_index": test_index, "utility": utility})

                for variant_name, feature_mode, selection_metric in VARIANTS:
                    progress(f"{label} training variant={variant_name} ({time.perf_counter() - started:.1f}s elapsed)")
                    model = train_variant(
                        train, test, teacher_groups_train, feature_mode, args.kmax, args.switch_beta,
                        args.epochs, selection_metric, args.validation_fraction,
                        args.pair_sampling, args.pairs_per_class, args.kmeans_n_init,
                    )
                    for test_index, scenario in enumerate(test):
                        groups = mvp.learned_grouping(scenario, model, args.kmax, args.switch_beta, args.kmeans_n_init)
                        utility = mvp.allocate_and_evaluate(groups, scenario, args.switch_beta).utility
                        rows.append({**tags, "method": f"LE-GRA[{variant_name}]", "test_index": test_index, "utility": utility})
    return rows


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def paired_diff(rows: list[dict], method_a: str, method_b: str) -> np.ndarray:
    by_unit: dict[tuple, dict] = {}
    for row in rows:
        unit = (row["scenario_mode"], row["load_level"], row["seed"], row["test_index"])
        by_unit.setdefault(unit, {})[row["method"]] = row["utility"]
    diffs = [v[method_a] - v[method_b] for v in by_unit.values() if method_a in v and method_b in v]
    return np.array(diffs, dtype=float)


def bootstrap_ci(diffs: np.ndarray, n_boot: int, rng: np.random.Generator) -> tuple[float, float, float, float]:
    if len(diffs) == 0:
        return float("nan"), float("nan"), float("nan"), float("nan")
    mean = float(diffs.mean())
    n = len(diffs)
    boot_means = np.empty(n_boot, dtype=float)
    for i in range(n_boot):
        boot_means[i] = diffs[rng.integers(0, n, size=n)].mean()
    lo, hi = np.percentile(boot_means, [2.5, 97.5])
    p_pos = float(np.mean(boot_means <= 0.0))
    p_neg = float(np.mean(boot_means >= 0.0))
    return mean, float(lo), float(hi), float(min(1.0, 2.0 * min(p_pos, p_neg)))


def holm_correction(p_values: list[float]) -> list[float]:
    order = sorted(range(len(p_values)), key=lambda i: p_values[i])
    adjusted = [0.0] * len(p_values)
    running_max = 0.0
    for rank, idx in enumerate(order):
        adj = (len(p_values) - rank) * p_values[idx]
        running_max = max(running_max, adj)
        adjusted[idx] = min(1.0, running_max)
    return adjusted


def summarize(rows: list[dict], n_boot: int, seed: int) -> list[dict]:
    rng = np.random.default_rng(seed)
    all_methods = BASELINE_METHODS + [f"LE-GRA[{name}]" for name, _, _ in VARIANTS]
    print("=== Mean utility per method (pooled) ===")
    for method in all_methods:
        values = [r["utility"] for r in rows if r["method"] == method]
        if values:
            print(f"  {method:28s} mean_utility={np.mean(values):.5f}  n={len(values)}")

    comparisons = [
        ("legra_full_none_vs_history_cost_none", "LE-GRA[full_none]", "LE-GRA[history_cost_none]"),
        ("legra_history_cost_utility_vs_none", "LE-GRA[history_cost_utility]", "LE-GRA[history_cost_none]"),
        ("legra_full_utility_vs_full_none", "LE-GRA[full_utility]", "LE-GRA[full_none]"),
        ("legra_full_utility_vs_history_cost_none", "LE-GRA[full_utility]", "LE-GRA[history_cost_none]"),
        ("legra_full_utility_vs_multifeature", "LE-GRA[full_utility]", "Multi-feature k-means"),
        ("legra_history_cost_none_vs_multifeature", "LE-GRA[history_cost_none]", "Multi-feature k-means"),
    ]
    records = []
    p_values = []
    for label, a, b in comparisons:
        diffs = paired_diff(rows, a, b)
        mean, lo, hi, p = bootstrap_ci(diffs, n_boot, rng)
        win_rate = float(np.mean(diffs > 0)) if len(diffs) else float("nan")
        records.append(
            {
                "comparison": label, "method_a": a, "method_b": b,
                "mean_diff_a_minus_b": mean, "ci95_lo": lo, "ci95_hi": hi,
                "p_value_raw": p, "p_value_holm": None,
                "win_rate_a_over_b": win_rate, "n_paired_units": len(diffs),
            }
        )
        p_values.append(p)
    adjusted = holm_correction(p_values)
    for record, adj in zip(records, adjusted):
        record["p_value_holm"] = adj

    print("\n=== Holm-corrected comparisons ===")
    for r in records:
        sig = "significant" if r["p_value_holm"] < 0.05 else "not significant"
        print(
            f"{r['comparison']}: mean(a-b)={r['mean_diff_a_minus_b']:+.5f} "
            f"CI=[{r['ci95_lo']:+.5f},{r['ci95_hi']:+.5f}] holm_p={r['p_value_holm']:.4f} "
            f"({sig}) win_rate={r['win_rate_a_over_b']:.3f} n={r['n_paired_units']}"
        )
    return records


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--train-scenarios", type=int, default=60)
    parser.add_argument("--test-scenarios", type=int, default=30)
    parser.add_argument("--users", type=int, default=24)
    parser.add_argument("--rbs", type=int, default=100)
    parser.add_argument("--epochs", type=int, default=12)
    parser.add_argument("--kmax", type=int, default=3)
    parser.add_argument("--switch-beta", type=float, default=0.5)
    parser.add_argument("--kmeans-n-init", type=int, default=10)
    parser.add_argument("--pair-sampling", choices=["random_balanced", "hard_negative"], default="random_balanced")
    parser.add_argument("--pairs-per-class", type=int, default=160)
    parser.add_argument("--validation-fraction", type=float, default=0.2)
    parser.add_argument("--scenario-modes", nargs="+", default=DEFAULT_SCENARIO_MODES)
    parser.add_argument("--load-levels", nargs="+", choices=list(LOAD_RATIOS), default=["light", "medium", "heavy"])
    parser.add_argument("--seeds", nargs="+", type=int, default=DEFAULT_SEEDS)
    parser.add_argument("--n-boot", type=int, default=10000)
    parser.add_argument("--bootstrap-seed", type=int, default=0)
    parser.add_argument("--out-dir", type=Path, default=Path("legra_algorithm_ablation_results"))
    args = parser.parse_args()

    started = time.perf_counter()
    progress(
        f"Pre-registered protocol: modes={args.scenario_modes}, loads={args.load_levels}, kmax={args.kmax}, "
        f"seeds={args.seeds}, train={args.train_scenarios}, test={args.test_scenarios}, epochs={args.epochs}, "
        f"validation_fraction={args.validation_fraction}"
    )
    rows = run_matrix(args)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(args.out_dir / "per_scenario_results.csv", rows)
    summary_rows = summarize(rows, n_boot=args.n_boot, seed=args.bootstrap_seed)
    write_csv(args.out_dir / "summary_stats.csv", summary_rows)
    progress(f"Done in {time.perf_counter() - started:.1f}s. Wrote {args.out_dir}/")


if __name__ == "__main__":
    main()
